spring.datasource.url=jdbc:mysql://localhost:3306/modulo_medicos_especialidades
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
<<<<<<< Updated upstream
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
=======
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
>>>>>>> Stashed changes
